from time import sleep
time_delay = 1
input("\n\n\n\n\n\n\n\n\n\n\nFor best experience put the terminal inbetween the 30th line of code and the 31st line of code (press enter when done)\n\n\n\n\n\n\n\n\n")
secretNumber = input("\n\n\n\n\n\n\n\nThink of a number and the computer will guess it: \n\n\n\n\n\n\n\n\n")

print("\n\n\n\n\n\n\n\nReading brain waves\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nReading brain waves.\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nReading brain waves..\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nReading brain waves...\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nReading brain waves..\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nReading brain waves.\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nReading brain waves\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben.\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben..\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben...\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben..\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben.\n\n\n\n\n\n\n\n")
sleep(time_delay)
print("\n\n\n\n\n\n\n\nBreaking down blooben\n\n\n\n\n\n\n\n")
time_delay = 3
sleep(time_delay)
print("The number you are thinking of is", secretNumber, "\n\n\n\n\n\n\n\n")